### ISSUE TITLE
Filename quoting issue with asymptote.sty and lualatex

### ISSUE THREAD

**Issue by lfourquaux** [vectorgraphics/asymptote#27]
This example file:

```
\documentclass{article}
\usepackage{asymptote}
\begin{document}
\begin{asy}
size(1cm);
draw(unitsquare);
\end{asy}
\end{document}
```

does not compile with lualatex.  It works fine with pdflatex. The error message is:

```
! error:  (file "bug-1".pdf) (pdf backend): cannot find image file '"bug-1".pdf'
!  ==> Fatal error occurred, no output PDF file produced!
```

It happens on the second run of lualatex, after processing the .asy file with asy.

The problem seems to be on line 309 of asymptote.sty: `\includegraphics[hiresbb]{"\AsyFile".pdf}` which adds extra quotes.

I'm not sure how quoting should be done, but this thread:
https://www.tug.org/pipermail/luatex/2016-March/005793.html
might be related and suggests that luatex is stricter than pdflatex but not buggy (w.r.t. quoted filenames).

**Comment by lfourquaux** [comment]
This is with TeXLive 2016.

**Comment by lfourquaux** [comment]
It looks like this is fixed in current TL 2016.

**Comment by u-fischer** [comment]
I don't think that the issue is fixed. On tex.sx there just has been a similar question: https://tex.stackexchange.com/questions/376401/asymptote-package-works-with-pdflatex-and-xelatex-but-problems-with-lualatex, 

And the asymptote.sty you get with texlive (2016/11/14 v1.32) still contains in various places quotes around the main part of a graphic. E.g `"\AsyFile".pdf`, and luatex doesn't like this (it isn't a problem of the graphicx drivers, it doesn't work with primitives either).

**Comment by johncbowman** [comment]
The quotes are necessary in order to handle file names containing spaces, which many users unfortunately insist on. If you remove the quotes, lualatex will work, but only with file names that do not contain spaces. I will check to see if lualatex in TeXLive 2017 has been fixed to discard quotation marks.

**Comment by u-fischer** [comment]
It still fails. But users that wants to use spaces can use the grffile package:

```
\documentclass{book}
\usepackage{graphicx}
\usepackage{grffile}
\begin{document}
\includegraphics{test space.pdf}

\includegraphics{test space} 
\end{document}

```

**Comment by matthuszagh** [comment]
This issue persists in texlive-2019. Maybe a reasonable compromise would be to commit the patch mentioned in [this issue](https://github.com/vectorgraphics/asymptote/issues/75) and require that luatex users use `grffile` if they want spaces in their files? At least that way the base case would work with luatex.

**Comment by johncbowman** [comment]
It turns out that a patched version of grffile now supports all TeXengines (including lualatex, xelatex, latex as well as pdflatex). So the simplest solution is to use grffile. I have committed this
as revision 41cc1fa54e638954177314a0add6b2d3a043257f, but I still have to update asymptote.sty.

**Comment by u-fischer** [comment]
This week patch level 2 of the current latex will be released, which will contain significant changes in the file name handling of graphicx. grffile will then be no longer needed, the package will be made to a no-op package.

**Comment by matthuszagh** [comment]
@johncbowman I'm experiencing the following issues when attempting to build asymptote:
```
Package asymptote Warning: file `latexusage-1.tex' not found on input line 76.
Package asymptote Warning: file `latexusage-2.tex' not found on input line 93.
Package asymptote Warning: file `latexusage-3.tex' not found on input line 117.
```
Is this possibly related to the pending changes to asymptote.sty?

**Comment by johncbowman** [comment]
That is normal. The next step generates those files (see LaTeX usage in the
manual):
asy latexusage-*.asy

**Comment by matthuszagh** [comment]
Thanks for the clarification on that. I thought that may have been causing the error I'm getting when building the documentation, but I guess it's something else. I'm seeing this
```
[...]
tex/latex/latexconfig/epstopdf-sys.cfg)) (./latexusage-1.tex)
! Missing } inserted.
<inserted text>
                }
l.76 \end{asy}

?
! Emergency stop.
<inserted text>
                }
l.76 \end{asy}

!  ==> Fatal error occurred, no output PDF file produced!
```
I guess I could download the pdf manually as mentioned in the install file, but I'd like to be able to build it if possible.
